apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
spec:
  containers:
  - name: dreact
    image: 044650439222.dkr.ecr.us-east-1.amazonaws.com/garima
    ports:
    - containerPort: 4100
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: react
    ports:
    - protocol: TCP
      port: 4100
      targetPort: 4100
